export default {
  LOAD_COURSES_SUCCESS: "LOAD_COURSES_SUCCESS",
  LOAD_AUTHORS_SUCCESS: "LOAD_AUTHORS_SUCCESS",
  UPDATE_COURSE_SUCCESS: "UPDATE_COURSE_SUCCESS",
  CREATE_COURSE_SUCCESS: "CREATE_COURSE_SUCCESS",
  BEGIN_API_CALL: "BEGIN_API_CALL",
  API_CALL_FAIL: "API_CALL_FAIL",
  DELETE_COURSE_OPTIMISTIC: "DELETE_COURSE_OPTIMISTIC",
};
